//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/ButtonMapping/PlayerButtonMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerButtonMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerButtonMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerButtonMap"",
    ""maps"": [
        {
            ""name"": ""PlayerActions"",
            ""id"": ""3e7ec655-7a2c-49c3-ba4f-f685c0af117f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""9cb52ed0-b1dd-4652-a038-aa985f712556"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f45c2726-fc09-4b97-a51b-5f42b3ff2f74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Couch"",
                    ""type"": ""Button"",
                    ""id"": ""caab91b4-6e31-4287-bd7e-0388f9f7a281"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpAttack"",
                    ""type"": ""Button"",
                    ""id"": ""46a0ab6c-edc6-4302-b4ac-19fb8265044a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightAttack"",
                    ""type"": ""Button"",
                    ""id"": ""999dc728-b5b5-40dc-8b19-4452b589104e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownAttack"",
                    ""type"": ""Button"",
                    ""id"": ""f16494be-e203-4ba8-a6d6-77c1da6473c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftAttack"",
                    ""type"": ""Button"",
                    ""id"": ""b3fa1613-a49a-4417-abb8-23f5c10e563a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""abdb24ea-0986-48b9-917f-365200c1fdb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSwitch1"",
                    ""type"": ""Button"",
                    ""id"": ""93aee480-64bb-4034-ab1c-d4f62c85dd67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSwitch2"",
                    ""type"": ""Button"",
                    ""id"": ""9e94682f-a179-48c3-bf9f-2127bdd2f6cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSwitch3"",
                    ""type"": ""Button"",
                    ""id"": ""3342d880-87ae-4348-9069-bb28a4d20b05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSwitch4"",
                    ""type"": ""Button"",
                    ""id"": ""e0e8abdd-0670-42c4-ab1f-1d58e29bbc28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSwitch5"",
                    ""type"": ""Button"",
                    ""id"": ""73ebcffe-9dee-4bbd-bba0-ad823e6fda6c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""dfd38ffc-b6f6-4e24-af3a-7f01a900741d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""96accf99-8986-4fcf-b1c6-7c54ebc1f759"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""a350cec1-7445-4191-bc17-ccd9b869bb06"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""f4f6d5e2-bd8b-4811-a060-2f7b2c2f05c3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""c555b206-5647-414b-a048-c2fd934e42a3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1fe126ef-54a0-433a-b878-c4283558a822"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Couch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0616a20c-e05c-4eee-9be6-a3177627b282"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5c281cc-0843-4029-84d4-c9e4e9a3fbc8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d6805e3-a7db-476f-9d63-d8d49b036fb3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c1c2844-c5cb-43b7-9241-d515cc009b6c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""897b2838-88ec-427b-af86-aa17e17522de"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3a371ac-2db8-4c78-ae88-e5e8d999ab53"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18c6e5a9-6d90-49d7-8aa1-658af59bccf6"",
                    ""path"": ""<Keyboard>/#(1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSwitch1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bc9608e-739f-4f28-806d-abc036ac2e5e"",
                    ""path"": ""<Keyboard>/#(2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSwitch2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28d02e36-78ac-4b31-91f9-7f8426012fe1"",
                    ""path"": ""<Keyboard>/#(3)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSwitch3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cfea55e-db0d-4fe8-92c1-198cd811ce72"",
                    ""path"": ""<Keyboard>/#(4)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSwitch4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb903bc0-ff9c-4964-b6b5-c2764b7841e8"",
                    ""path"": ""<Keyboard>/#(5)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSwitch5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerActions
        m_PlayerActions = asset.FindActionMap("PlayerActions", throwIfNotFound: true);
        m_PlayerActions_Movement = m_PlayerActions.FindAction("Movement", throwIfNotFound: true);
        m_PlayerActions_Jump = m_PlayerActions.FindAction("Jump", throwIfNotFound: true);
        m_PlayerActions_Couch = m_PlayerActions.FindAction("Couch", throwIfNotFound: true);
        m_PlayerActions_UpAttack = m_PlayerActions.FindAction("UpAttack", throwIfNotFound: true);
        m_PlayerActions_RightAttack = m_PlayerActions.FindAction("RightAttack", throwIfNotFound: true);
        m_PlayerActions_DownAttack = m_PlayerActions.FindAction("DownAttack", throwIfNotFound: true);
        m_PlayerActions_LeftAttack = m_PlayerActions.FindAction("LeftAttack", throwIfNotFound: true);
        m_PlayerActions_Interaction = m_PlayerActions.FindAction("Interaction", throwIfNotFound: true);
        m_PlayerActions_WeaponSwitch1 = m_PlayerActions.FindAction("WeaponSwitch1", throwIfNotFound: true);
        m_PlayerActions_WeaponSwitch2 = m_PlayerActions.FindAction("WeaponSwitch2", throwIfNotFound: true);
        m_PlayerActions_WeaponSwitch3 = m_PlayerActions.FindAction("WeaponSwitch3", throwIfNotFound: true);
        m_PlayerActions_WeaponSwitch4 = m_PlayerActions.FindAction("WeaponSwitch4", throwIfNotFound: true);
        m_PlayerActions_WeaponSwitch5 = m_PlayerActions.FindAction("WeaponSwitch5", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActions
    private readonly InputActionMap m_PlayerActions;
    private List<IPlayerActionsActions> m_PlayerActionsActionsCallbackInterfaces = new List<IPlayerActionsActions>();
    private readonly InputAction m_PlayerActions_Movement;
    private readonly InputAction m_PlayerActions_Jump;
    private readonly InputAction m_PlayerActions_Couch;
    private readonly InputAction m_PlayerActions_UpAttack;
    private readonly InputAction m_PlayerActions_RightAttack;
    private readonly InputAction m_PlayerActions_DownAttack;
    private readonly InputAction m_PlayerActions_LeftAttack;
    private readonly InputAction m_PlayerActions_Interaction;
    private readonly InputAction m_PlayerActions_WeaponSwitch1;
    private readonly InputAction m_PlayerActions_WeaponSwitch2;
    private readonly InputAction m_PlayerActions_WeaponSwitch3;
    private readonly InputAction m_PlayerActions_WeaponSwitch4;
    private readonly InputAction m_PlayerActions_WeaponSwitch5;
    public struct PlayerActionsActions
    {
        private @PlayerButtonMap m_Wrapper;
        public PlayerActionsActions(@PlayerButtonMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerActions_Movement;
        public InputAction @Jump => m_Wrapper.m_PlayerActions_Jump;
        public InputAction @Couch => m_Wrapper.m_PlayerActions_Couch;
        public InputAction @UpAttack => m_Wrapper.m_PlayerActions_UpAttack;
        public InputAction @RightAttack => m_Wrapper.m_PlayerActions_RightAttack;
        public InputAction @DownAttack => m_Wrapper.m_PlayerActions_DownAttack;
        public InputAction @LeftAttack => m_Wrapper.m_PlayerActions_LeftAttack;
        public InputAction @Interaction => m_Wrapper.m_PlayerActions_Interaction;
        public InputAction @WeaponSwitch1 => m_Wrapper.m_PlayerActions_WeaponSwitch1;
        public InputAction @WeaponSwitch2 => m_Wrapper.m_PlayerActions_WeaponSwitch2;
        public InputAction @WeaponSwitch3 => m_Wrapper.m_PlayerActions_WeaponSwitch3;
        public InputAction @WeaponSwitch4 => m_Wrapper.m_PlayerActions_WeaponSwitch4;
        public InputAction @WeaponSwitch5 => m_Wrapper.m_PlayerActions_WeaponSwitch5;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Couch.started += instance.OnCouch;
            @Couch.performed += instance.OnCouch;
            @Couch.canceled += instance.OnCouch;
            @UpAttack.started += instance.OnUpAttack;
            @UpAttack.performed += instance.OnUpAttack;
            @UpAttack.canceled += instance.OnUpAttack;
            @RightAttack.started += instance.OnRightAttack;
            @RightAttack.performed += instance.OnRightAttack;
            @RightAttack.canceled += instance.OnRightAttack;
            @DownAttack.started += instance.OnDownAttack;
            @DownAttack.performed += instance.OnDownAttack;
            @DownAttack.canceled += instance.OnDownAttack;
            @LeftAttack.started += instance.OnLeftAttack;
            @LeftAttack.performed += instance.OnLeftAttack;
            @LeftAttack.canceled += instance.OnLeftAttack;
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
            @WeaponSwitch1.started += instance.OnWeaponSwitch1;
            @WeaponSwitch1.performed += instance.OnWeaponSwitch1;
            @WeaponSwitch1.canceled += instance.OnWeaponSwitch1;
            @WeaponSwitch2.started += instance.OnWeaponSwitch2;
            @WeaponSwitch2.performed += instance.OnWeaponSwitch2;
            @WeaponSwitch2.canceled += instance.OnWeaponSwitch2;
            @WeaponSwitch3.started += instance.OnWeaponSwitch3;
            @WeaponSwitch3.performed += instance.OnWeaponSwitch3;
            @WeaponSwitch3.canceled += instance.OnWeaponSwitch3;
            @WeaponSwitch4.started += instance.OnWeaponSwitch4;
            @WeaponSwitch4.performed += instance.OnWeaponSwitch4;
            @WeaponSwitch4.canceled += instance.OnWeaponSwitch4;
            @WeaponSwitch5.started += instance.OnWeaponSwitch5;
            @WeaponSwitch5.performed += instance.OnWeaponSwitch5;
            @WeaponSwitch5.canceled += instance.OnWeaponSwitch5;
        }

        private void UnregisterCallbacks(IPlayerActionsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Couch.started -= instance.OnCouch;
            @Couch.performed -= instance.OnCouch;
            @Couch.canceled -= instance.OnCouch;
            @UpAttack.started -= instance.OnUpAttack;
            @UpAttack.performed -= instance.OnUpAttack;
            @UpAttack.canceled -= instance.OnUpAttack;
            @RightAttack.started -= instance.OnRightAttack;
            @RightAttack.performed -= instance.OnRightAttack;
            @RightAttack.canceled -= instance.OnRightAttack;
            @DownAttack.started -= instance.OnDownAttack;
            @DownAttack.performed -= instance.OnDownAttack;
            @DownAttack.canceled -= instance.OnDownAttack;
            @LeftAttack.started -= instance.OnLeftAttack;
            @LeftAttack.performed -= instance.OnLeftAttack;
            @LeftAttack.canceled -= instance.OnLeftAttack;
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
            @WeaponSwitch1.started -= instance.OnWeaponSwitch1;
            @WeaponSwitch1.performed -= instance.OnWeaponSwitch1;
            @WeaponSwitch1.canceled -= instance.OnWeaponSwitch1;
            @WeaponSwitch2.started -= instance.OnWeaponSwitch2;
            @WeaponSwitch2.performed -= instance.OnWeaponSwitch2;
            @WeaponSwitch2.canceled -= instance.OnWeaponSwitch2;
            @WeaponSwitch3.started -= instance.OnWeaponSwitch3;
            @WeaponSwitch3.performed -= instance.OnWeaponSwitch3;
            @WeaponSwitch3.canceled -= instance.OnWeaponSwitch3;
            @WeaponSwitch4.started -= instance.OnWeaponSwitch4;
            @WeaponSwitch4.performed -= instance.OnWeaponSwitch4;
            @WeaponSwitch4.canceled -= instance.OnWeaponSwitch4;
            @WeaponSwitch5.started -= instance.OnWeaponSwitch5;
            @WeaponSwitch5.performed -= instance.OnWeaponSwitch5;
            @WeaponSwitch5.canceled -= instance.OnWeaponSwitch5;
        }

        public void RemoveCallbacks(IPlayerActionsActions instance)
        {
            if (m_Wrapper.m_PlayerActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActionsActions @PlayerActions => new PlayerActionsActions(this);
    public interface IPlayerActionsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCouch(InputAction.CallbackContext context);
        void OnUpAttack(InputAction.CallbackContext context);
        void OnRightAttack(InputAction.CallbackContext context);
        void OnDownAttack(InputAction.CallbackContext context);
        void OnLeftAttack(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
        void OnWeaponSwitch1(InputAction.CallbackContext context);
        void OnWeaponSwitch2(InputAction.CallbackContext context);
        void OnWeaponSwitch3(InputAction.CallbackContext context);
        void OnWeaponSwitch4(InputAction.CallbackContext context);
        void OnWeaponSwitch5(InputAction.CallbackContext context);
    }
}
